name: build executables

on:
  push:
    tags:
      - "v*"

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@master
        with: { python-version: 3.9 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip PyInstaller

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: build
        run: pyinstaller splatnet2statink.py --onefile --icon=s2s.ico

      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: splatnet2statink-Windows
          path: dist/splatnet2statink.exe

  # macOS-build:
  #   runs-on: macOS-latest
  #   steps:
  #     - name: Checkout commit
  #       uses: actions/checkout@master

  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@master
  #       with: { python-version: 3.9 }

  #     - name: Upgrade pip
  #       run: python -m pip install --upgrade pip PyInstaller

  #     - name: Install requirements
  #       run: pip install -r requirements.txt

  #     - name: build
  #       run: pyinstaller -F splatnet2statink.py

  #     - name: upload
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: splatnet2statink-macos
  #         path: dist/splatnet2statink

  # ubuntu-build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout commit
  #       uses: actions/checkout@master

  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@master
  #       with: { python-version: 3.9 }

  #     - name: Upgrade pip
  #       run: python -m pip install --upgrade pip PyInstaller

  #     - name: Install requirements
  #       run: pip install -r requirements.txt

  #     - name: build
  #       run: pyinstaller -F splatnet2statink.py

  #     - name: upload
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: splatnet2statink-linux
  #         path: dist/splatnet2statink

  release:
    # needs: [ubuntu-build, macOS-build, windows-build]
    # runs-on: ubuntu-latest
    needs: [windows-build]
    runs-on: ubuntu-latest

    steps:
      # - name: Download Linux
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: splatnet2statink-linux

      # - name: Download Mac
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: splatnet2statink-macos

      - name: Download Windows
        uses: actions/download-artifact@v1
        with:
          name: splatnet2statink-Windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Zip
        # run: |
        #   tar -C splatnet2statink-macos -pczvf splatnet2statink-macos.tar.gz splatnet2statink
        #   tar -C splatnet2statink-linux -pczvf splatnet2statink-linux.tar.gz splatnet2statink
        #   zip --junk-paths splatnet2statink-Windows ./splatnet2statink-Windows/splatnet2statink.exe
        run: zip --junk-paths splatnet2statink-${{ github.ref }}Windows ./splatnet2statink-Windows/splatnet2statink.exe
      # - name: Append Binary
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./splatnet2statink-macos.tar.gz
      #     asset_name: splatnet2statink-macos.tar.gz
      #     asset_content_type: application/gzip

      # - name: Append Binary
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./splatnet2statink-linux.tar.gz
      #     asset_name: splatnet2statink-linux.tar.gz
      #     asset_content_type: application/gzip

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./splatnet2statink-${{ github.ref }}-Windows.zip
          asset_name: splatnet2statink-${{ github.ref }}-Windows.zip
          asset_content_type: application/zip